# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a24bc31d49120864bae2e85b6ca72afa172900d933e4f96ef47d50bfc8939bcdf8a6e05f2aa624c5777563cee397849f06d6f3a216d946c54b4b00eca620aba

test:
  secret_key_base: 417d071bf32682958f0cc5194eb583d6134815d2b71f464b0af6b1e3394812c481fbef20bb50f8158531d08c86d416dd67d8ede28caa338e17ec47da38c064e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
